SilverStripe\Control\Director:
  rules:
    'GoogleRecaptcha' : 'ContextualSoftware\GoogleRecaptcha\Controllers\GoogleReCaptchaController'

ContextualSoftware\GoogleRecaptcha\Controllers\GoogleReCaptchaController:
  verification_endpoint:
    'https://www.google.com/recaptcha/api/siteverify'
